### ISSUE TITLE
Update nginx config to handle HTTPS/SSL

### ISSUE THREAD

**Issue by unzico** [farmhelden/farmhelden-client#10]
Wenn ich richtig sehe, handhabt unsere nginx.conf bislang nur http-Protokolle.
Seiten, die keine HTTPS-Verbindung haben, werden unter anderem in der Google Suche geblockt bzw. von Browsern blockiert.

Deswegen sollten wir unsere Config anpassen.
Hat jemand damit Erfahrung?
Hätte eventuell eine rudimentäre Config dafür.

**Comment by FlorianGerhardt** [comment]
Das wird von traefik bereits gemacht.
