### ISSUE TITLE
Add <Calendar/> component

### ISSUE THREAD

**Issue by unzico** [farmhelden/farmhelden-client#36]
Derzeitiger Draft für das UI: https://overflow.io/s/XLSJFJ?node=87756cd9

Wir benötigen für unser Boarding einen Kalender, wie in **Inserat-anlegen_002_01** und **Inserat-anlegen_002_02** zu sehen ist.

Mein Vorschlag wäre folgendes:
- Name: `Calendar`
- Pfad: `components/Calendar`
- Library: [**react-calendar**](https://github.com/wojtekmaj/react-calendar#readme)

Meinungen?
Wäre das vllt etwas für dich @fabriz-io ?

**Comment by fabriz-io** [comment]
Jap, mache mich dran

**Comment by unzico** [comment]
Closed in #42
