### ISSUE TITLE
Add formik to handle forms

### ISSUE THREAD

**Issue by unzico** [farmhelden/farmhelden-client#7]
Habe ebenfalls gute Erfahrungen mit [**formik**](https://github.com/jaredpalmer/formik) gemacht, weswegen ich es in diesem Projekt auch einsetzen würde, um die Formulare zu handhaben.

**Comment by Cogitri** [comment]
* Formular wird genutzt für:
    * Filtern nach Anzeigen
    * Formular um Anzeigen aufzugeben.

**Comment by unzico** [comment]
Closed in #16
