### ISSUE TITLE
Integrate mapbox to handle maps

### ISSUE THREAD

**Issue by unzico** [farmhelden/farmhelden-client#9]
Wir haben uns ja darauf festgelegt, [**mapbox**](https://www.mapbox.com/) für Karten zu integrieren. 

@FlorianGerhardt: Möchtest Du die Integration vielleicht übernehmen? Eine einfache Map-Komponente, die wir wiederverwenden können, wäre zunächst am sinnvollsten, denke ich.

**Quellen:**
- [mapbox and react](https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/)
- [mapbox npm package](https://www.npmjs.com/package/mapbox-gl)

**Comment by FlorianGerhardt** [comment]
Yo, mach ich!

**Comment by unzico** [comment]
Closed in #15
